repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-check
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        args: [-w, -s, -i, '4']

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: nargo-fmt
        name: Format Noir code
        entry: bash
        args: [-c, 'for dir in $(find . -name "Nargo.toml" -exec dirname {} \;); do echo "Formatting Noir files in $dir"; (cd "$dir" && nargo fmt); done']
        language: system
        files: \.nr$
        pass_filenames: false
        always_run: false
        require_serial: true
