[project]
name = "just_cps_to_log_return"
version = "0.1.0"
description = "Checkpoint to log return calculator"
authors = [{ name = "Inference Labs Inc" }]
dependencies = ["argparse>=1.4.0", "matplotlib>=3.10.3", "numpy>=1.24.0"]
